name: fnf
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.6.5
  - numpy=1.17.4
  - scipy=1.3.2
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - jupyterlab
  - scikit-learn=0.22.1
  - seaborn
  - cytoolz
  - bokeh
  - yellowbrick
  - pip:
    - gensim==3.8.1
    - tensorflow==1.14
    - tensorflow_hub
    - sentencepiece
    - spacy==2.2.3
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.2.0/en_core_web_md-2.2.0.tar.gz

  # Tooling requirements
    - tqdm
    - pyyaml
    - tables
    - black
    - blackcellmagic
    - pymysql
    - sqlalchemy
    - dvc
    - click
    - Sphinx
    - sphinxcontrib.napoleon
    - coverage
    - awscli
    - flake8
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
